import QtQml
import qs.services

QtObject {
    function groupProfile() { return { mode: "generic+custom", strategies: ["exact", "prefix", "compact", "substring", "acronym", "fuzzy", "semantic"], scorePolicy: "default", profile: { evidence: ["field-match:all", "switch-action", "semantic"], inherit: ["path-evidence"], boost: ["descendant-boost"], childVisible: ["visible-flag"], tokenFlow: ["consume-namespace-pass-rest"], takeoverRequest: ["child-own-match-parent-no-own-match", "explicit-child-token", "child-covers-passed-tokens", "own-score-dominates-takeover"], takeoverAccept: ["accept-dominated-claims"], expand: ["expand-on-own-match-or-trailing-space"], retainParent: [{ name: "retain-parent-when", args: { condition: "own-match" } }], defaultAction: ["default-action-expand"], riskGate: ["risk-gate"] } }; }
    function roots(context) { return [audioTree(), brightnessTree()]; }
    function audioTree() { return { id: "audio", aliases: ["audio", "sound", "volume", "mute"], title: qsTr("Audio"), icon: AudioService.outputIconName, iconColor: AudioService.outputMuted ? Config.styling.critical : Config.styling.secondaryAccent, template: "flat-action-group", behavior: { filterChildren: true, selectable: false }, evaluationProfile: groupProfile(), children: AudioService.outputDeviceEntries().map(function(entry) { return { id: "sink-" + entry.id, aliases: ["sink", "output", "speaker", entry.name], title: entry.name, subtitle: entry.default ? qsTr("Default output") : qsTr("Output"), icon: entry.iconName, iconColor: entry.muted ? Config.styling.critical : Config.styling.secondaryAccent, template: "flat-action-group", behavior: { filterChildren: true }, evaluationProfile: groupProfile(), switchState: entry.muted, control: entry.control, switchActions: entry.switchActions, children: streamChildren(entry.id) }; }) }; }
    function streamChildren(outputId) { var streams = AudioService.streamEntriesForOutput(outputId); return streams.length > 0 ? [{ id: "streams", aliases: ["streams", "apps", "applications"], title: qsTr("Streams"), subtitle: streams.length + " " + qsTr("active"), icon: "audio-x-generic-symbolic", iconColor: Config.styling.text1, template: "flat-action-group", behavior: { filterChildren: true }, evaluationProfile: groupProfile(), children: streams.map(function(stream) { return { id: "stream-" + stream.id, aliases: ["stream", "volume", stream.name], title: stream.name, subtitle: stream.volume + "%", icon: stream.iconName, iconColor: stream.muted ? Config.styling.critical : Config.styling.secondaryAccent, switchState: stream.muted, control: stream.control, switchActions: stream.switchActions }; }) }] : []; }
    function brightnessTree() { return { id: "brightness", aliases: ["brightness", "backlight", "screen"], title: qsTr("Brightness"), subtitle: Brightness.available ? qsTr("Screen brightness") : qsTr("Backlight unavailable"), icon: Brightness.iconName, iconColor: Brightness.available ? Config.styling.primaryAccent : Config.styling.text2, template: "flat-action-group", behavior: { filterChildren: true }, evaluationProfile: groupProfile(), children: [{ id: "brightness-volume", aliases: ["brightness", "level", "slider"], title: qsTr("Brightness"), subtitle: Brightness.available ? (Brightness.percent + "%") : qsTr("Unavailable"), icon: Brightness.iconName, iconColor: Brightness.available ? Config.styling.primaryAccent : Config.styling.text2, control: { kind: "slider", target: "brightness", from: 0, to: 100, step: 5, value: Brightness.percent } }] }; }
}
