---@class LuaLsOptions
---@field completion? table
---@field diagnostics? table
---@field format? table
---@field hint? table
---@field runtime? table
---@field workspace? table

return {
    settings = {
        ---@type LuaLsOptions
        Lua = {
            format = {
                enable = true,
                defaultConfig = {
                    align_array_table = "true",
                    align_call_args = "false",
                    align_chain_expr = "none",
                    align_continuous_assign_statement = "true",
                    align_continuous_inline_comment = "true",
                    align_continuous_line_space = "2",
                    align_continuous_rect_table_field = "true",
                    align_continuous_similar_call_args = "false",
                    align_function_params = "true",
                    align_if_branch = "false",
                    allow_non_indented_comments = "false",
                    auto_collapse_lines = "false",
                    break_all_list_when_line_exceed = "false",
                    break_before_braces = "false",
                    call_arg_parentheses = "keep",
                    continuation_indent = "4",
                    detect_end_of_line = "false",
                    end_of_line = "unset",
                    end_statement_with_semicolon = "keep",
                    ignore_space_after_colon = "false",
                    ignore_spaces_inside_function_call = "false",
                    indent_size = "4",
                    indent_style = "space",
                    insert_final_newline = "true",
                    keep_indents_on_empty_lines = "false",
                    line_space_after_comment = "keep",
                    line_space_after_do_statement = "keep",
                    line_space_after_expression_statement = "keep",
                    line_space_after_for_statement = "keep",
                    line_space_after_function_statement = "fixed(2)",
                    line_space_after_if_statement = "keep",
                    line_space_after_local_or_assign_statement = "keep",
                    line_space_after_repeat_statement = "keep",
                    line_space_after_while_statement = "keep",
                    line_space_around_block = "fixed(1)",
                    max_line_length = "120",
                    never_indent_before_if_condition = "false",
                    never_indent_comment_on_if_branch = "false",
                    quote_style = "double",
                    remove_call_expression_list_finish_comma = "false",
                    space_after_comma = "true",
                    space_after_comma_in_for_statement = "true",
                    space_after_comment_dash = "false",
                    space_around_assign_operator = "true",
                    space_around_concat_operator = "true",
                    space_around_logical_operator = "true",
                    space_around_math_operator = "true",
                    space_around_table_append_operator = "false",
                    space_around_table_field_list = "true",
                    space_before_attribute = "true",
                    space_before_closure_open_parenthesis = "true",
                    space_before_function_call_open_parenthesis = "false",
                    space_before_function_call_single_arg = "always",
                    space_before_function_open_parenthesis = "false",
                    space_before_inline_comment = "1",
                    space_before_open_square_bracket = "false",
                    space_inside_function_call_parentheses = "false",
                    space_inside_function_param_list_parentheses = "false",
                    space_inside_square_brackets = "false",
                    tab_width = "4",
                    table_separator_style = "comma",
                    trailing_table_separator = "smart",
                },
            },
            runtime = {
                version = "LuaJIT",
            },
            diagnostics = {
                globals = {
                    "vim",
                    "Ui",
                    "StatusColumn",
                    "StatusLine",
                    "TabLine",
                },
            },
            workspace = {
                checkThirdParty = "false",
                library = {
                    unpack(vim.api.nvim_get_runtime_file("", true)),
                    "${3rd}/luv/library",
                    "${3rd}/busted/library",
                },
            },
            hint = {
                enable = false,
                arrayIndex = "Auto",
                await = true,
                paramName = "All",
                paramType = true,
                semicolon = "All",
                setType = true,
            },
        },
    },
}
